#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/klee-miuicamera

PRODUCT_COPY_FILES += \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/102_SummerDay.png:$(TARGET_COPY_OUT_ODM)/etc/camera/102_SummerDay.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/103_Fantasy.png:$(TARGET_COPY_OUT_ODM)/etc/camera/103_Fantasy.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/104_Meet.png:$(TARGET_COPY_OUT_ODM)/etc/camera/104_Meet.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/105_WindSing.png:$(TARGET_COPY_OUT_ODM)/etc/camera/105_WindSing.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/106_Lost.png:$(TARGET_COPY_OUT_ODM)/etc/camera/106_Lost.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/107_Central.png:$(TARGET_COPY_OUT_ODM)/etc/camera/107_Central.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/108_NorthernEurope.png:$(TARGET_COPY_OUT_ODM)/etc/camera/108_NorthernEurope.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/109_Rome.png:$(TARGET_COPY_OUT_ODM)/etc/camera/109_Rome.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/110_BlackGold.png:$(TARGET_COPY_OUT_ODM)/etc/camera/110_BlackGold.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/111_GreenOrange.png:$(TARGET_COPY_OUT_ODM)/etc/camera/111_GreenOrange.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/112_CyberPunk.png:$(TARGET_COPY_OUT_ODM)/etc/camera/112_CyberPunk.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/113_BlackIce.png:$(TARGET_COPY_OUT_ODM)/etc/camera/113_BlackIce.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/121_Bleach.png:$(TARGET_COPY_OUT_ODM)/etc/camera/121_Bleach.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/122_Thriller.png:$(TARGET_COPY_OUT_ODM)/etc/camera/122_Thriller.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/123_TealOrange.png:$(TARGET_COPY_OUT_ODM)/etc/camera/123_TealOrange.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/124_JapaneseStyle.png:$(TARGET_COPY_OUT_ODM)/etc/camera/124_JapaneseStyle.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/125_Latin.png:$(TARGET_COPY_OUT_ODM)/etc/camera/125_Latin.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/126_Fantasy2.png:$(TARGET_COPY_OUT_ODM)/etc/camera/126_Fantasy2.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/127_Creamy.png:$(TARGET_COPY_OUT_ODM)/etc/camera/127_Creamy.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/128_Sepia.png:$(TARGET_COPY_OUT_ODM)/etc/camera/128_Sepia.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/129_Vivid.png:$(TARGET_COPY_OUT_ODM)/etc/camera/129_Vivid.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/130_Natural.png:$(TARGET_COPY_OUT_ODM)/etc/camera/130_Natural.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/131_Monochrome.png:$(TARGET_COPY_OUT_ODM)/etc/camera/131_Monochrome.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/132_MonochromeHighContrast.png:$(TARGET_COPY_OUT_ODM)/etc/camera/132_MonochromeHighContrast.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/133_MonochromeBrown.png:$(TARGET_COPY_OUT_ODM)/etc/camera/133_MonochromeBrown.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/134_MonochromeBlue.png:$(TARGET_COPY_OUT_ODM)/etc/camera/134_MonochromeBlue.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/135_Classical.png:$(TARGET_COPY_OUT_ODM)/etc/camera/135_Classical.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/136_Filene.png:$(TARGET_COPY_OUT_ODM)/etc/camera/136_Filene.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/137_GreenNight.png:$(TARGET_COPY_OUT_ODM)/etc/camera/137_GreenNight.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/138_LiteratureAndArt.png:$(TARGET_COPY_OUT_ODM)/etc/camera/138_LiteratureAndArt.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/139_OrangeHoney.png:$(TARGET_COPY_OUT_ODM)/etc/camera/139_OrangeHoney.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/140_Romance.png:$(TARGET_COPY_OUT_ODM)/etc/camera/140_Romance.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/141_FR500.png:$(TARGET_COPY_OUT_ODM)/etc/camera/141_FR500.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/142_FE250.png:$(TARGET_COPY_OUT_ODM)/etc/camera/142_FE250.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/143_RedLantern.png:$(TARGET_COPY_OUT_ODM)/etc/camera/143_RedLantern.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/144_RedHero.png:$(TARGET_COPY_OUT_ODM)/etc/camera/144_RedHero.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/145_TactileBlackWhite.png:$(TARGET_COPY_OUT_ODM)/etc/camera/145_TactileBlackWhite.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/146_TactileGreen.png:$(TARGET_COPY_OUT_ODM)/etc/camera/146_TactileGreen.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/147_Neutral.png:$(TARGET_COPY_OUT_ODM)/etc/camera/147_Neutral.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/148_Mild.png:$(TARGET_COPY_OUT_ODM)/etc/camera/148_Mild.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/149_LilyWhite.png:$(TARGET_COPY_OUT_ODM)/etc/camera/149_LilyWhite.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/150_Bright.png:$(TARGET_COPY_OUT_ODM)/etc/camera/150_Bright.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/151_Fresh.png:$(TARGET_COPY_OUT_ODM)/etc/camera/151_Fresh.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/152_Limpid.png:$(TARGET_COPY_OUT_ODM)/etc/camera/152_Limpid.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/153_KC64.png:$(TARGET_COPY_OUT_ODM)/etc/camera/153_KC64.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/154_V250.png:$(TARGET_COPY_OUT_ODM)/etc/camera/154_V250.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/155_H400.png:$(TARGET_COPY_OUT_ODM)/etc/camera/155_H400.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/156_ColdWhite.png:$(TARGET_COPY_OUT_ODM)/etc/camera/156_ColdWhite.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/157_Native.png:$(TARGET_COPY_OUT_ODM)/etc/camera/157_Native.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/158_BWClassical.png:$(TARGET_COPY_OUT_ODM)/etc/camera/158_BWClassical.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/159_Flowers.png:$(TARGET_COPY_OUT_ODM)/etc/camera/159_Flowers.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/160_vivid.png:$(TARGET_COPY_OUT_ODM)/etc/camera/160_vivid.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/161_wind.png:$(TARGET_COPY_OUT_ODM)/etc/camera/161_wind.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/162_nature.png:$(TARGET_COPY_OUT_ODM)/etc/camera/162_nature.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/163_free.png:$(TARGET_COPY_OUT_ODM)/etc/camera/163_free.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/164_fc400.png:$(TARGET_COPY_OUT_ODM)/etc/camera/164_fc400.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/165_c_50d.png:$(TARGET_COPY_OUT_ODM)/etc/camera/165_c_50d.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/166_revert.png:$(TARGET_COPY_OUT_ODM)/etc/camera/166_revert.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/72.png:$(TARGET_COPY_OUT_ODM)/etc/camera/72.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/73.png:$(TARGET_COPY_OUT_ODM)/etc/camera/73.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/AIGesture/buling_1s.png:$(TARGET_COPY_OUT_ODM)/etc/camera/AIGesture/buling_1s.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/AIGesture/buling_2s.png:$(TARGET_COPY_OUT_ODM)/etc/camera/AIGesture/buling_2s.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/AIGesture/buling_3s.png:$(TARGET_COPY_OUT_ODM)/etc/camera/AIGesture/buling_3s.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/AIGesture/buling_4s.png:$(TARGET_COPY_OUT_ODM)/etc/camera/AIGesture/buling_4s.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/AIGesture/buling_5s.png:$(TARGET_COPY_OUT_ODM)/etc/camera/AIGesture/buling_5s.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/AIGesture/circle_1.png:$(TARGET_COPY_OUT_ODM)/etc/camera/AIGesture/circle_1.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/AIGesture/circle_2.png:$(TARGET_COPY_OUT_ODM)/etc/camera/AIGesture/circle_2.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/AIGesture/circle_3.png:$(TARGET_COPY_OUT_ODM)/etc/camera/AIGesture/circle_3.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/AIGesture/circle_4.png:$(TARGET_COPY_OUT_ODM)/etc/camera/AIGesture/circle_4.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/AIGesture/circle_5.png:$(TARGET_COPY_OUT_ODM)/etc/camera/AIGesture/circle_5.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/AIGesture/circle_6.png:$(TARGET_COPY_OUT_ODM)/etc/camera/AIGesture/circle_6.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/AIGesture/clip_1.png:$(TARGET_COPY_OUT_ODM)/etc/camera/AIGesture/clip_1.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/AIGesture/clip_2.png:$(TARGET_COPY_OUT_ODM)/etc/camera/AIGesture/clip_2.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/AIGesture/clip_3.png:$(TARGET_COPY_OUT_ODM)/etc/camera/AIGesture/clip_3.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/AIGesture/clip_4.png:$(TARGET_COPY_OUT_ODM)/etc/camera/AIGesture/clip_4.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/AIGesture/clip_5.png:$(TARGET_COPY_OUT_ODM)/etc/camera/AIGesture/clip_5.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/AIGesture/clip_6.png:$(TARGET_COPY_OUT_ODM)/etc/camera/AIGesture/clip_6.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/AIGesture/clip_7.png:$(TARGET_COPY_OUT_ODM)/etc/camera/AIGesture/clip_7.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/AIGesture/heart_1s.png:$(TARGET_COPY_OUT_ODM)/etc/camera/AIGesture/heart_1s.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/AIGesture/heart_2s.png:$(TARGET_COPY_OUT_ODM)/etc/camera/AIGesture/heart_2s.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/AIGesture/heart_3s.png:$(TARGET_COPY_OUT_ODM)/etc/camera/AIGesture/heart_3s.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/AIGesture/heart_4s.png:$(TARGET_COPY_OUT_ODM)/etc/camera/AIGesture/heart_4s.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/AIGesture/heart_5s.png:$(TARGET_COPY_OUT_ODM)/etc/camera/AIGesture/heart_5s.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/AIGesture/heart_6s.png:$(TARGET_COPY_OUT_ODM)/etc/camera/AIGesture/heart_6s.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/AIGesture/thumbup_3s.png:$(TARGET_COPY_OUT_ODM)/etc/camera/AIGesture/thumbup_3s.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/videofilter/102_SummerDay.png:$(TARGET_COPY_OUT_ODM)/etc/camera/videofilter/102_SummerDay.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/videofilter/103_Fantasy.png:$(TARGET_COPY_OUT_ODM)/etc/camera/videofilter/103_Fantasy.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/videofilter/104_Meet.png:$(TARGET_COPY_OUT_ODM)/etc/camera/videofilter/104_Meet.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/videofilter/105_WindSing.png:$(TARGET_COPY_OUT_ODM)/etc/camera/videofilter/105_WindSing.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/videofilter/106_Lost.png:$(TARGET_COPY_OUT_ODM)/etc/camera/videofilter/106_Lost.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/videofilter/107_Central.png:$(TARGET_COPY_OUT_ODM)/etc/camera/videofilter/107_Central.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/videofilter/108_NorthernEurope.png:$(TARGET_COPY_OUT_ODM)/etc/camera/videofilter/108_NorthernEurope.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/videofilter/109_Rome.png:$(TARGET_COPY_OUT_ODM)/etc/camera/videofilter/109_Rome.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/videofilter/110_BlackGold.png:$(TARGET_COPY_OUT_ODM)/etc/camera/videofilter/110_BlackGold.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/videofilter/111_GreenOrange.png:$(TARGET_COPY_OUT_ODM)/etc/camera/videofilter/111_GreenOrange.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/videofilter/112_CyberPunk.png:$(TARGET_COPY_OUT_ODM)/etc/camera/videofilter/112_CyberPunk.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/videofilter/113_BlackIce.png:$(TARGET_COPY_OUT_ODM)/etc/camera/videofilter/113_BlackIce.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/videofilter/121_Bleach.png:$(TARGET_COPY_OUT_ODM)/etc/camera/videofilter/121_Bleach.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/videofilter/122_Thriller.png:$(TARGET_COPY_OUT_ODM)/etc/camera/videofilter/122_Thriller.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/videofilter/123_TealOrange.png:$(TARGET_COPY_OUT_ODM)/etc/camera/videofilter/123_TealOrange.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/videofilter/124_JapaneseStyle.png:$(TARGET_COPY_OUT_ODM)/etc/camera/videofilter/124_JapaneseStyle.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/videofilter/125_Latin.png:$(TARGET_COPY_OUT_ODM)/etc/camera/videofilter/125_Latin.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/videofilter/126_Fantasy2.png:$(TARGET_COPY_OUT_ODM)/etc/camera/videofilter/126_Fantasy2.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/videofilter/127_Creamy.png:$(TARGET_COPY_OUT_ODM)/etc/camera/videofilter/127_Creamy.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/videofilter/128_Sepia.png:$(TARGET_COPY_OUT_ODM)/etc/camera/videofilter/128_Sepia.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/videofilter/129_LeicaVivid.png:$(TARGET_COPY_OUT_ODM)/etc/camera/videofilter/129_LeicaVivid.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/videofilter/129_Vivid.png:$(TARGET_COPY_OUT_ODM)/etc/camera/videofilter/129_Vivid.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/videofilter/130_LeicaNatural.png:$(TARGET_COPY_OUT_ODM)/etc/camera/videofilter/130_LeicaNatural.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/videofilter/130_Natural.png:$(TARGET_COPY_OUT_ODM)/etc/camera/videofilter/130_Natural.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/videofilter/131_MonochromeTrue.png:$(TARGET_COPY_OUT_ODM)/etc/camera/videofilter/131_MonochromeTrue.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/videofilter/132_MonochromeHighContrast.png:$(TARGET_COPY_OUT_ODM)/etc/camera/videofilter/132_MonochromeHighContrast.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/videofilter/133_MonochromeBrown.png:$(TARGET_COPY_OUT_ODM)/etc/camera/videofilter/133_MonochromeBrown.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/videofilter/134_MonochromeBlue.png:$(TARGET_COPY_OUT_ODM)/etc/camera/videofilter/134_MonochromeBlue.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/videofilter/135_Classical.png:$(TARGET_COPY_OUT_ODM)/etc/camera/videofilter/135_Classical.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/videofilter/136_Filene.png:$(TARGET_COPY_OUT_ODM)/etc/camera/videofilter/136_Filene.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/videofilter/137_GreenNight.png:$(TARGET_COPY_OUT_ODM)/etc/camera/videofilter/137_GreenNight.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/videofilter/138_LiteratureAndArt.png:$(TARGET_COPY_OUT_ODM)/etc/camera/videofilter/138_LiteratureAndArt.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/videofilter/139_OrangeHoney.png:$(TARGET_COPY_OUT_ODM)/etc/camera/videofilter/139_OrangeHoney.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/videofilter/140_Romance.png:$(TARGET_COPY_OUT_ODM)/etc/camera/videofilter/140_Romance.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/videofilter/141_FR500.png:$(TARGET_COPY_OUT_ODM)/etc/camera/videofilter/141_FR500.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/videofilter/142_FE250.png:$(TARGET_COPY_OUT_ODM)/etc/camera/videofilter/142_FE250.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/videofilter/143_RedLantern.png:$(TARGET_COPY_OUT_ODM)/etc/camera/videofilter/143_RedLantern.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/videofilter/144_RedHero.png:$(TARGET_COPY_OUT_ODM)/etc/camera/videofilter/144_RedHero.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/videofilter/145_TactileBlackWhite.png:$(TARGET_COPY_OUT_ODM)/etc/camera/videofilter/145_TactileBlackWhite.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/videofilter/146_TactileGreen.png:$(TARGET_COPY_OUT_ODM)/etc/camera/videofilter/146_TactileGreen.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/videofilter/147_Neutral.png:$(TARGET_COPY_OUT_ODM)/etc/camera/videofilter/147_Neutral.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/videofilter/148_Mild.png:$(TARGET_COPY_OUT_ODM)/etc/camera/videofilter/148_Mild.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/videofilter/149_LilyWhite.png:$(TARGET_COPY_OUT_ODM)/etc/camera/videofilter/149_LilyWhite.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/videofilter/150_Bright.png:$(TARGET_COPY_OUT_ODM)/etc/camera/videofilter/150_Bright.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/videofilter/151_Fresh.png:$(TARGET_COPY_OUT_ODM)/etc/camera/videofilter/151_Fresh.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/videofilter/152_Limpid.png:$(TARGET_COPY_OUT_ODM)/etc/camera/videofilter/152_Limpid.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/videofilter/153_KC64.png:$(TARGET_COPY_OUT_ODM)/etc/camera/videofilter/153_KC64.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/videofilter/154_V250.png:$(TARGET_COPY_OUT_ODM)/etc/camera/videofilter/154_V250.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/videofilter/155_H400.png:$(TARGET_COPY_OUT_ODM)/etc/camera/videofilter/155_H400.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/videofilter/156_ColdWhite.png:$(TARGET_COPY_OUT_ODM)/etc/camera/videofilter/156_ColdWhite.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/videofilter/157_Native.png:$(TARGET_COPY_OUT_ODM)/etc/camera/videofilter/157_Native.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/videofilter/158_BWClassical.png:$(TARGET_COPY_OUT_ODM)/etc/camera/videofilter/158_BWClassical.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/videofilter/159_Flowers.png:$(TARGET_COPY_OUT_ODM)/etc/camera/videofilter/159_Flowers.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/videofilter/160_Vivid.png:$(TARGET_COPY_OUT_ODM)/etc/camera/videofilter/160_Vivid.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/videofilter/161_KP160.png:$(TARGET_COPY_OUT_ODM)/etc/camera/videofilter/161_KP160.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/videofilter/162_Natural.png:$(TARGET_COPY_OUT_ODM)/etc/camera/videofilter/162_Natural.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/videofilter/163_KG200.png:$(TARGET_COPY_OUT_ODM)/etc/camera/videofilter/163_KG200.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/videofilter/164_FC400.png:$(TARGET_COPY_OUT_ODM)/etc/camera/videofilter/164_FC400.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/videofilter/165_C50D.png:$(TARGET_COPY_OUT_ODM)/etc/camera/videofilter/165_C50D.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/videofilter/166_F50.png:$(TARGET_COPY_OUT_ODM)/etc/camera/videofilter/166_F50.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/videofilter/167_CC.png:$(TARGET_COPY_OUT_ODM)/etc/camera/videofilter/167_CC.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/videofilter/168_NC.png:$(TARGET_COPY_OUT_ODM)/etc/camera/videofilter/168_NC.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/videofilter/169_LeicaChrome.png:$(TARGET_COPY_OUT_ODM)/etc/camera/videofilter/169_LeicaChrome.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/videofilter/170_LeicaClassic.png:$(TARGET_COPY_OUT_ODM)/etc/camera/videofilter/170_LeicaClassic.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/videofilter/171_LeicaContemporary.png:$(TARGET_COPY_OUT_ODM)/etc/camera/videofilter/171_LeicaContemporary.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/videofilter/172_LeicaEternal.png:$(TARGET_COPY_OUT_ODM)/etc/camera/videofilter/172_LeicaEternal.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/videofilter/173_LeicaBrass.png:$(TARGET_COPY_OUT_ODM)/etc/camera/videofilter/173_LeicaBrass.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/videofilter/174_LeicaTeal.png:$(TARGET_COPY_OUT_ODM)/etc/camera/videofilter/174_LeicaTeal.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/videofilter/175_LeicaIModelA.png:$(TARGET_COPY_OUT_ODM)/etc/camera/videofilter/175_LeicaIModelA.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/MiSans-Demibold.ttf:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/MiSans-Demibold.ttf \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/MiSans-Medium.ttf:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/MiSans-Medium.ttf \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/MiSans-Regular.ttf:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/MiSans-Regular.ttf \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/MiSansArabicVF.ttf:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/MiSansArabicVF.ttf \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/MiSansTibetanVF.ttf:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/MiSansTibetanVF.ttf \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/Noto-COLRv1-emojicompat.ttf:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/Noto-COLRv1-emojicompat.ttf \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/Oxanium-Medium.ttf:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/Oxanium-Medium.ttf \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_cv_film_logo.png:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_cv_film_logo.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_cv_film_logo_white.png:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_cv_film_logo_white.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_cv_logo.png:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_cv_logo.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_cv_logo_p3.png:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_cv_logo_p3.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_cv_poco_logo.png:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_cv_poco_logo.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_cv_poco_logo_white.png:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_cv_poco_logo_white.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_cv_redmi_logo.png:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_cv_redmi_logo.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_cv_redmi_logo_white.png:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_cv_redmi_logo_white.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_cv_xiaomi_logo.png:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_cv_xiaomi_logo.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_cv_xiaomi_logo_white.png:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_cv_xiaomi_logo_white.png \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_0100_c.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_0100_c.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_0101.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_0101.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_0101_c.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_0101_c.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_0214.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_0214.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_0601.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_0601.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_0815_c.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_0815_c.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_1208_c.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_1208_c.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_1225.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_1225.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_agra_fort.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_agra_fort.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_amber_fort.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_amber_fort.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_beauty_charm.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_beauty_charm.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_beijing.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_beijing.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_bluesky.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_bluesky.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_buddha.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_buddha.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_cat.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_cat.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_cat_c.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_cat_c.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_chengdu.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_chengdu.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_chongqing.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_chongqing.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_cloudy.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_cloudy.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_coconut_tree.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_coconut_tree.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_coffee.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_coffee.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_coffee_c.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_coffee_c.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_cow.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_cow.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_curry.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_curry.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_delicacy.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_delicacy.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_diwali.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_diwali.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_dog.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_dog.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_dog_c.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_dog_c.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_dussehra.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_dussehra.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_elephant_god.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_elephant_god.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_fleshiness.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_fleshiness.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_flower.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_flower.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_gateway_delhi.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_gateway_delhi.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_gateway_mumbai.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_gateway_mumbai.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_grassplot.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_grassplot.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_great_wall.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_great_wall.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_gu_lang_island.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_gu_lang_island.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_guangzhou.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_guangzhou.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_hang_ya_cave.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_hang_ya_cave.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_hangzhou.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_hangzhou.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_happy_time.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_happy_time.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_holi.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_holi.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_huoguo.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_huoguo.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_kids.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_kids.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_kids_c.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_kids_c.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_leafs.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_leafs.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_monkey.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_monkey.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_motorcycle.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_motorcycle.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_mount_huang.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_mount_huang.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_namaste.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_namaste.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_nanjing.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_nanjing.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_nightscape.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_nightscape.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_overcast.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_overcast.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_party_time.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_party_time.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_plants.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_plants.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_rakhi.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_rakhi.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_red_fort.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_red_fort.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_republic_day.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_republic_day.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_shanghai.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_shanghai.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_sunrise_sunset.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_sunrise_sunset.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_super_moon_airplane.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_super_moon_airplane.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_super_moon_black_cat.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_super_moon_black_cat.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_super_moon_branch_bird.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_super_moon_branch_bird.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_super_moon_cable_car.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_super_moon_cable_car.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_super_moon_climb.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_super_moon_climb.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_super_moon_flying_bird.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_super_moon_flying_bird.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_super_moon_leaf.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_super_moon_leaf.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_super_moon_text_1.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_super_moon_text_1.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_super_moon_text_2.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_super_moon_text_2.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_super_moon_text_3.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_super_moon_text_3.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_super_moon_text_4.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_super_moon_text_4.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_super_moon_text_5.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_super_moon_text_5.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_super_moon_text_7.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_super_moon_text_7.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_super_moon_text_8.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_super_moon_text_8.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_super_moon_window.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_super_moon_window.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_suzhou.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_suzhou.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_suzhou_gardens.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_suzhou_gardens.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_taj_mahal.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_taj_mahal.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_temple_of_heaven.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_temple_of_heaven.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_the_palace_museum.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_the_palace_museum.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_the_potala_palace.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_the_potala_palace.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_the_summer_palace.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_the_summer_palace.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_the_terracotta_army.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_the_terracotta_army.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_tianjin.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_tianjin.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_tutuk.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_tutuk.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_underwater.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_underwater.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_victoria_harbor.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_victoria_harbor.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_west_lake.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_west_lake.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_wuhan.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_wuhan.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/ic_wp_zhang_jia_jie.webp:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/ic_wp_zhang_jia_jie.webp \
    vendor/xiaomi/klee-miuicamera/proprietary/odm/etc/camera/xiaomi/watermark/noise_logo.png:$(TARGET_COPY_OUT_ODM)/etc/camera/xiaomi/watermark/noise_logo.png \
    vendor/xiaomi/klee-miuicamera/proprietary/system_ext/etc/permissions/vendor.xiaomi.hardware.misys-V1.0-java-permission.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/vendor.xiaomi.hardware.misys-V1.0-java-permission.xml \
    vendor/xiaomi/klee-miuicamera/proprietary/system_ext/etc/permissions/vendor.xiaomi.hardware.misys-V2.0-java-permission.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/vendor.xiaomi.hardware.misys-V2.0-java-permission.xml \
    vendor/xiaomi/klee-miuicamera/proprietary/system_ext/etc/permissions/vendor.xiaomi.hardware.misys-V4.0-java-permission.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/vendor.xiaomi.hardware.misys-V4.0-java-permission.xml \
    vendor/xiaomi/klee-miuicamera/proprietary/system_ext/etc/permissions/vendor.xiaomi.hardware.misys.V3_0-permission.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/vendor.xiaomi.hardware.misys.V3_0-permission.xml \
    vendor/xiaomi/klee-miuicamera/proprietary/vendor/etc/init/vendor.xiaomi.hardware.misys.core-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.xiaomi.hardware.misys.core-service.rc

PRODUCT_PACKAGES += \
    vendor.xiaomi.hardware.misys.common-V3-ndk \
    vendor.xiaomi.hardware.mtkblackbox-V3-ndk \
    libmisys_jni.xiaomi \
    vendor.xiaomi.hardware.misys@1.0 \
    vendor.xiaomi.hardware.misys@3.0 \
    libcamera_algoup_jni.xiaomi \
    libcamera_ispinterface_jni.xiaomi \
    libcamera_mianode_jni.xiaomi \
    libmtkisp_metadata_sys \
    vendor.mediatek.hardware.camera.isphal-V1-ndk-system_ext \
    vendor.mediatek.hardware.camera.isphal@1.0-system_ext \
    vendor.xiaomi.hardware.misys.common-V3-ndk-system_ext \
    vendor.xiaomi.hardware.misys.core-V1-ndk-system_ext \
    MiuiCamera \
    mediatek-framework \
    vendor.xiaomi.hardware.misys-V1.0-java \
    vendor.xiaomi.hardware.misys-V2.0-java \
    vendor.xiaomi.hardware.misys-V4.0-java \
    vendor.xiaomi.hardware.misys.V3_0 \
    vendor.xiaomi.hardware.misys.common-V2-java \
    vendor.xiaomi.hardware.misys.common.xml \
    vendor.xiaomi.hardware.misys.core.xml \
    vendor.xiaomi.hardware.misys.core-service \
    hypsys_vendor

PRODUCT_BOOT_JARS += \
    mediatek-framework
